/* Generated By:JavaCC: Do not edit this line. SimpleSelectParserConstants.java */
package cn.com.ptpress.cdm.parser.select;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleSelectParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 1;
  /** RegularExpression Id. */
  int NUMBER = 2;
  /** RegularExpression Id. */
  int ADD = 3;
  /** RegularExpression Id. */
  int SUB = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"SELECT\"",
    "<NUMBER>",
    "\"+\"",
    "\"-\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
  };

}
